sudo: required
dist: trusty
language: python
cache: pip3
python:
  - "3.5"
# command to install dependencies
install:
  - cd tests
  - sudo apt-get -y install python3-pip
  - pip3 install bs4
script: 
  - python3 test_getemails.py
