sudo: required
dist: trusty
language: python
cache: pip3
python:
  - "3.6"
# command to install dependencies
install:
  - sudo apt-get -y install python3-pip
  - pip3 install -r requirements.txt
  - cd modules/tests
before_script:
  - pip install -r test_requirements.txt
  - git clone https://github.com/z4r/python-coveralls-example.git
  - cd python-coveralls-example
  - git checkout -qf 3e82fd5159b84bebe9bc6c9fd3959f322e6f7098
  - py.test example/tests.py --cov=example
script: 
  - pytest
  - cd -
  - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
notifications:
    slack: dedsec-inside:24NHg47gypeVR3DWnEncRq7c
after_success:
  - coveralls