sudo: required
dist: trusty
language: python
cache: pip3
python:
  - "3.6"
# command to install dependencies
install:
  - sudo apt-get -y install python3-pip
  - pip3 install -r requirements.txt
  - cd modules/tests
  - pip3 install python-coveralls
script: 
  - pytest --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
notifications:
    slack: dedsec-inside:24NHg47gypeVR3DWnEncRq7c
after_success:
  - coveralls