language: python
python:
  - "3.5"
# command to install dependencies
before_install:
  - cd test
  - sudo apt-get -y install python3-pip
  - pip3 install bs4
script: 
  - python tests/test_getemails.py
